{
 "title": "Locust",
 "tags": [ "locust" ],
 "time": { "from": "2019-09-08T16:45:04.654Z", "to": "2019-09-08T16:46:11.947Z" },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"success\" = 'True'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fail",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"success\" = 'False'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Totals by HTTP Verb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "DELETE",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'DELETE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GET",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'GET'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HEAD",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'HEAD'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "POST",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'POST'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUT",
   "type": "singlestat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'PUT'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "RPS Over Time",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY time(1s), \"request_type\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time Over Time",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"response_time\"\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY \"request_type\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}